// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeoTvz5N9aTREaEl5J8qxBBqQuTdKEcFw',
    appId: '1:47363290752:web:dc32cf5f8efa26b0e35865',
    messagingSenderId: '47363290752',
    projectId: 'crudfirebase-ffaed',
    authDomain: 'crudfirebase-ffaed.firebaseapp.com',
    storageBucket: 'crudfirebase-ffaed.appspot.com',
    measurementId: 'G-FKFE4MHWFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcfCgVQ_sHVRIir_2siNZmN76aVUu8-14',
    appId: '1:47363290752:android:7fdcd208db9ae2dae35865',
    messagingSenderId: '47363290752',
    projectId: 'crudfirebase-ffaed',
    storageBucket: 'crudfirebase-ffaed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDARQIi0OCbtRIzeaOGaFxO1Yf-35dbXPQ',
    appId: '1:47363290752:ios:2358bf7231d24598e35865',
    messagingSenderId: '47363290752',
    projectId: 'crudfirebase-ffaed',
    storageBucket: 'crudfirebase-ffaed.appspot.com',
    iosBundleId: 'com.example.firebase',
  );


}
